### ISSUE TITLE
Ошибка зума при Undo/Redo

### ISSUE THREAD

**Issue by pishivi** [RengaSoftware/ModelExplorer#11]
Пример:
- Разместить на сцене 3 колонны (желательно, не вплотную, чтобы видеть изменения камеры)
- Открыть плагин. Селектировать папку "колонны", выбрать команду "Показать объект"
- Камера меняет свое расположение: вид сверху, в зуме все три колонны
- На счене жмём Undo
- В плагине, не обновляя его, жмём "Показать объект"
- Камера меняет свое расположение: вид сверху, в зуме две оставшиеся колонны
- На сцене жмём Redo
- В плагине, не обновляя его, снова жмём на "Показать объект"
**[B]: Камера не меняет расположения. Несмотря на то, что на сцене снова три колонны, в зум попадают только две**

**Comment by tyan** [comment]
На данный момент не ошибка. Это поведение само собой исправится, когда плагин станет реагировать на события модели.
