### ISSUE TITLE
Отобразить все типы свойств

### ISSUE THREAD

**Issue by Magnum1988** [RengaSoftware/ModelExplorer#12]
Добрый день, какие свойства попадают в обозреватель, я добавил свойство для воздухораспределителей, но в свойсвтвах объекта они не появились, хотя через правую кнопку по объекту свойства есть

Спасибо

**Comment by tyan** [comment]
Здравствуйте! В обозреватель модели на данный момент попадают все свойства объектов. Возможно вы не нажали кнопку "Обновить", на данный момент плагин не реагирует на изменения в модели.
Если вы добавили свойство на объект типа "Вентиляционное оборудование", то оно должно быть. Если добавили на стиль оборудования, то тогда оно не отобразится. Но мы прямо сейчас дорабатываем плагин, чтобы он отображал и эти свойства.

**Comment by Magnum1988** [comment]
Я как понял там не все типы свойств показываются, только целые числа и текст


Ещё было бы круто если бы плагин запоминал свое местоположение на экране и
размер

чт, 18 мар. 2021 г., 14:21 Evgeniy Tyan ***@***.***>:

**Comment by tyan** [comment]
Вы правы, это тоже поправим. Плагин развивается с опозданием от Renga.
Что вы имеете в виду под запоминанием местоположения? Что-то вроде этого?
https://1.bp.blogspot.com/-sfDyp0e8EUg/X_1yZ4jcEkI/AAAAAAAAB2s/FleDuCwkImct-76eN805i7RHSy31x_XhQCNcBGAsYHQ/s1280/viewpoint.gif

**Comment by Magnum1988** [comment]
не, само окно плагина, после перезапуска ренги становится как было по
умолчанию, приходиться каждый раз двигать окно, расширять и тд, плюс было
бы круто если в плагине нажал свернуть параметры, то при переключении на
другой элемент, список не раскрывался опять

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 18 мар. 2021 г. в 15:18, Evgeniy Tyan ***@***.***>:

**Comment by tyan** [comment]
Понял. Пока не планировали это. Но конечно логично иметь собственные настройки окна. Про переоткрывание списка заведу ошибку.

**Comment by Magnum1988** [comment]
Ещё может плагин сможет отслеживать положение объекта относительно уровня
где он находится и нуля проекта? Это очень полезная функция, которой были
рады бы все)

пт, 19 мар. 2021 г., 11:07 Evgeniy Tyan ***@***.***>:

**Comment by tyan** [comment]
Просто выводить высоту относительно уровня и земли?

**Comment by Magnum1988** [comment]
Да, типа низ компонента, середина и вверх было бы идеально

пт, 19 мар. 2021 г., 12:21 Evgeniy Tyan ***@***.***>:

**Comment by tyan** [comment]
Сохранение положения окна будет добавлено в ближайшем релизе. По поводу отображения свойств добавляю отдельный Issue, по поводу высоты верха/низа - посмотрите, должны отображаться все параметры, которые есть в объектах Renga, а там есть такие, насколько я помню.

**Comment by Magnum1988** [comment]
Вот например решетка
[image: image.png]

она явно не на нуле находиться, только смещение работает, хотелось бы
свойства которые бы показывали высоту установки оборудования, воздуховодов
и тд, как я собственно писал, грубо говоря как в ревите (если вы с ним
знакомы)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 28 мар. 2021 г. в 16:00, Evgeniy Tyan ***@***.***>:

**Comment by tyan** [comment]
Картинка не прикрепилась. 
Этот плагин не добавляет параметров объектам Renga, он только их отображает.
Сейчас есть такие параметры как Object bottom elevation, Object top elevation. Если не хватает каких-то параметров, то нужно писать в техподдержку системы именно.

**Comment by Magnum1988** [comment]
Ну эти элеаейшегы показываются, нужны именно отметки ( я думал плагин из
может выдернуть из недр ренги) и показать, просто сама то ренга знает где
висит это воздуховод например на какой отметке, где то внутри. Напишу в тех
поддержку

вт, 30 мар. 2021 г., 14:10 Evgeniy Tyan ***@***.***>:

**Comment by Magnum1988** [comment]
Хотя нет я не прав, вот эти отметки и нужны, чтобы они показались в плагине
дна и вверха

вт, 30 мар. 2021 г., 14:47 Magnum ***@***.***>:

**Comment by Magnum1988** [comment]
[image: image.png] вот сюда бы эти параметры добавить если гугл транслейт
их правильно перевел, то это отметка дна и верха?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 30 мар. 2021 г. в 14:10, Evgeniy Tyan ***@***.***>:

**Comment by Magnum1988** [comment]
> Картинка не прикрепилась((

https://cdn1.radikalno.ru/uploads/2021/3/31/13420aa89d6245aa528d643c08240b8e-full.png

**Comment by tyan** [comment]
Все типы свойств добавлены.
