### ISSUE TITLE
Долгое открытие в больших проектах

### ISSUE THREAD

**Issue by av-voronov** [RengaSoftware/ModelExplorer#47]
В проекте объёмом порядка 200 Мб обозреватель модели открывается около 10 минут. С чем может быть связано? Проблема в коде плагина или в API Renga? Возможно ли исправление ситуации?

**Comment by tyan** [comment]
Будем смотреть. Начать надо с плагина, конечно.

**Comment by tyan** [comment]
Есть замедление на стороне Renga. Будет поправлено в ближайшем релизе. Есть небольшое замедление на стороне плагина. Будем править, но сроков пока назвать не могу. После исправлений в Renga должно стать сильно лучше.

**Comment by tyan** [comment]
Внесены исправления на уровне Renga 8.2, также добавлены оптимизации в плагин.
