### ISSUE TITLE
Пожелания

### ISSUE THREAD

**Issue by nskhv** [RengaSoftware/ModelExplorer#8]
1) Просьба добавить 3д-линии в Обозреватель модели для просмотра их свойств (длина, высота, проекция по X/Y/Z и пр.)
2) https://vk.com/topic-102792196_34813100?post=787

**Comment by tyan** [comment]
Здравствуйте, хорошо, сделаем в следующем релизе плагина.

**Comment by tyan** [comment]
АПИ пока не готово для этого.
